CREATE TABLE IF NOT EXISTS assessment_attempts (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  attempt_id TEXT NOT NULL,
  status TEXT DEFAULT 'in_progress' NOT NULL,
  current_stage TEXT DEFAULT 'round1' NOT NULL,
  candidate_name TEXT NOT NULL,
  candidate_email TEXT DEFAULT '' NOT NULL,
  candidate_code TEXT DEFAULT '' NOT NULL,
  role TEXT NOT NULL,
  started_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  last_saved_at TEXT NOT NULL,
  completed_at TEXT,
  time_spent_seconds INTEGER DEFAULT 0 NOT NULL,
  auto_submitted INTEGER DEFAULT 0 NOT NULL,
  round1_score INTEGER,
  round1_total INTEGER,
  round1_band TEXT,
  round1_breakdown TEXT,
  delegation_plan TEXT DEFAULT '' NOT NULL,
  key_findings TEXT DEFAULT '' NOT NULL,
  recommendation TEXT DEFAULT '' NOT NULL,
  risks TEXT DEFAULT '' NOT NULL,
  executive_summary TEXT DEFAULT '' NOT NULL,
  verification_notes TEXT DEFAULT '' NOT NULL,
  chat_transcript TEXT DEFAULT '[]' NOT NULL,
  ai_call_count INTEGER DEFAULT 0 NOT NULL,
  grading_status TEXT DEFAULT 'not_started' NOT NULL,
  grader_result TEXT,
  round2_overall INTEGER,
  round2_band TEXT,
  round2_scores TEXT,
  grading_version TEXT DEFAULT 'talemy-4d-rubric-v3.0' NOT NULL,
  assessment_version TEXT DEFAULT 'talemy-4d-v3.0' NOT NULL,
  skipped_round1 INTEGER DEFAULT 0 NOT NULL,
  round2_state TEXT DEFAULT '{}' NOT NULL,
  delegation_state TEXT DEFAULT '{}' NOT NULL,
  final_result TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS assessment_attempts_attempt_id_unique ON assessment_attempts (attempt_id);
CREATE INDEX IF NOT EXISTS assessment_attempts_status_idx ON assessment_attempts (status);
CREATE INDEX IF NOT EXISTS assessment_attempts_created_at_idx ON assessment_attempts (created_at);
